### PR TITLE
testing

### PR DESCRIPTION
**Pull request by Naoki95957**
like the unstable branch, but a test for me to branch and a test for methods

### CODE REVIEW

**Comment by open-sourceress** [comment]
This can also be done by command-line: `git checkout unstable` `git merge master`

**Comment by Naoki95957** [comment]
I'm constantly denied access every time i try pushing to a branch other than master. Idk if I'm doing it wrong XD

**Comment by open-sourceress** [comment]
What's the specific error? I know you can't Ctrl-C out of Shell, but give me as much as you can.

**Comment by Naoki95957** [comment]
its a fairly consistent error. its a 403. Says remote: permission to ... denied to ... \n fatal: unable to access "url"

so the "url" is the url and the \n isn't actually there xD. the ellipses are .git files

**Comment by open-sourceress** [comment]
Run Github (the white circle with the purple cat). It will let you log in to Git, and you'll be able to commit.
Fun fact: 403 is server denied access. The most common usage I've seen is requiring users to log in.

**Comment by Naoki95957** [comment]
I'm logged in and still receive the same errors. I don't want to really push the code because I haven't got a computer to test it with and it involves the encoders. I made an update to your pidtalon class and in the case of the coffin bot, the encoders have different pulses on the front and back

**Comment by Naoki95957** [comment]
I also have simple movement methods that aim to aid autonomous

**Comment by Naoki95957** [comment]
it fails to publish the branch i want

**Comment by open-sourceress** [comment]
You have done `git add` and `git commit`, and you're doing `git push origin unstable`?

**Comment by Naoki95957** [comment]
yes, precisely

**Comment by open-sourceress** [comment]
Testing as we speak. I had to update (`git pull origin unstable`) just now, but the error didn't mention 403.

**Comment by Naoki95957** [comment]
I can pull, it's the pushing.

**Comment by open-sourceress** [comment]
I managed to get myself in a pickle, where Git wouldn't let me push (`remote has work that you don't`) but wouldn't let me pull either ('everything up-to-date`). I just deleted the project, created a new Robot,`init`'ed,`pull`ed, edited, and`push`ed. Everything worked.

**Comment by Naoki95957** [comment]
I sent an email and both gitshell and gitHub applications give me the same thing. I'll try sweeping it all out and then pushing.

**Comment by open-sourceress** [comment]
No need. Don't wipe it.

**Comment by open-sourceress** [comment]
The problem was that Software team was not associated with the repository, for some reason. I fixed it now, so you should be able to push. If not, wait a minute or to for the settings to take effect.

**Comment by open-sourceress** [comment]
I was able to push because I'm in Owners, who have unlimited access to everything.

**Comment by Naoki95957** [comment]
Yup! works now! thx

**Pull request merged**
